wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/train.py
    python_version: 3.9.9
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.34.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699492664.425958
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 41
      - 45
      - 49
      - 51
      - 55
      - 71
      - 83
      - 105
      2:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 41
      - 45
      - 49
      - 51
      - 55
      - 71
      - 83
      - 105
      3:
      - 23
      4: 3.9.9
      5: 0.15.12
      6: 4.34.0.dev0
      8:
      - 4
      - 5
      13: darwin-arm64
